
import { NavItem, Product } from './types';

export const VIVO_BLUE = '#00D4C6';

export const NAV_ITEMS: NavItem[] = [
  { label: 'nav_pro3', href: '#home' },
  { label: 'nav_foldable', href: '#foldable' },
  { label: 'nav_notebook', href: '#notebook' },
  { label: 'nav_store', href: '#store' },
  { label: 'nav_telecom', href: '#telecom' },
  { label: 'nav_chat', href: '#holographic' },
  { label: 'nav_fintech', href: '#fintech' },
  { label: 'nav_fitness', href: '#fitness' },
  { label: 'nav_cv', href: '#cv-maker' },
  { label: 'nav_tax', href: '#nova-tax' },
];

export const HERO_SLIDES = [
  {
    id: 1,
    image: 'https://fit-4rce-x.s3.eu-north-1.amazonaws.com/Metaball_liquid_wt_bg.mp4',
    title: 'S3Ts Pro 3.0',
    subtitle: '',
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'pro3',
    name: 'S3Ts Pro 3.0',
    tagline: '',
    image: 'https://fit-4rce-x.s3.eu-north-1.amazonaws.com/S3Ts_grey_rectoverso-transparent.png',
    series: 'X',
    price: 'SAR 6,375.00',
    specs: [
      'Aerospace Titanium Alpha Alloy',
      'Neural Core A2X (48 AI Cores)',
      'Nano-Optic Solar Cells (Lithium-Free)',
      'Holographic Beam Engine 3D Display',
      'Quantum-Link Global Satellite Internet'
    ]
  },
  {
    id: 'foldable',
    name: 'SUMĀMAH F',
    tagline: '',
    image: 'https://fit-4rce-x.s3.eu-north-1.amazonaws.com/Sumamah-F_folder.jpg',
    series: 'X',
    price: 'SAR 8,999.00',
    specs: [
      'Dual-Form Factor Foldable Design',
      'Integrated High-Precision Tactile Keyboard',
      'Neural Core A2X Architecture',
      'Star-Link Quantum Connection',
      'Solar-Skin Energy Harvesting'
    ]
  },
  {
    id: 'notebook',
    name: 'SUMĀMAH Aura',
    tagline: '',
    image: 'https://fit-4rce-x.s3.eu-north-1.amazonaws.com/Sumamah-aura_recto-text.jpg',
    series: 'X',
    price: 'SAR 14,989.00',
    specs: [
      'Pure Chrome-Finished Aluminum Body',
      'Full-Lid Solar Horizon Array',
      'Zero Battery Tech (72H Pulse Reserve)',
      'Desktop-Grade Neural Core A2X',
      'Active Silent Cooling System'
    ]
  }
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    nav_pro3: 'Pro 3.0',
    nav_foldable: 'SUMĀMAH F',
    nav_notebook: 'SUMĀMAH Aura',
    nav_store: 'Store',
    nav_chat: 'S3Ts Chat',
    nav_telecom: 'Telecom',
    nav_fintech: 'S3Ts Fintech',
    nav_fitness: 'S3Ts Fitness',
    nav_cv: 'S3Ts CV Master',
    nav_tax: 'S3Ts NovaTax',
    nav_search: 'Search',
    nav_account: 'Account',
    hero_title: 'S3Ts Pro 3.0',
    hero_cta: '',
    tech_chat: 'S3Ts Chat',
    tech_chat_desc: 'Next-generation encrypted communication.',
    bio_tag: 'Neural Core A2X',
    bio_title: 'Quantum Intelligence',
    bio_desc: '48 Dedicated AI cores processing at 14nm quantum neural threads.',
    energy_tag: 'Solar Optics',
    energy_title: 'Zero Lithium',
    energy_desc: 'Nano-optic solar cells provide infinite energy from the sun.',
    energy_lifespan: 'Perpetual',
    energy_reserve: '72H Reserve',
    tech_title: 'The Collection',
    tech_subtitle: '',
    footer_products: 'Products',
    footer_support: 'Support',
    footer_explore: 'Explore',
    footer_legal: 'Legal',
    footer_lang: 'English',
    store_crumb: 'Store',
    store_tagline: '',
    store_price: 'Price',
    store_stock: 'Available',
    store_finish: 'Finish',
    store_core: 'Neural Engine',
    store_core_name: 'S3Ts Neural Core A2X',
    store_included: 'Standard',
    store_add: 'Add to Bag',
    store_view_specs: 'Technical Specifications',
    store_warranty_title: 'S3Ts Care',
    store_warranty_desc: '2-Year Global Protection',
    store_solar_title: 'Solar Warranty',
    store_solar_desc: 'Infinite Health Guaranteed',
    foldable_title: 'SUMĀMAH F',
    foldable_intro: "In a world demanding both agility and depth, the SUMĀMAH FoldKey delivers. This isn't just a foldable smartphone; it's a re-imagination of mobile productivity, engineered for those who refuse to compromise on communication.",
    foldable_f1_t: "Tactile Command",
    foldable_f1_d: "Unfold to reveal a precisely engineered physical mini-keyboard, offering unparalleled typing speed and accuracy for emails, documents, and secure messaging—a true communicator's dream.",
    foldable_f2_t: "Infinite Power",
    foldable_f2_d: "Powered by our revolutionary Zero Battery, 100% Solar technology, the FoldKey ensures your thoughts are never interrupted by a low charge. With a 72-hour power reserve, your productivity flows seamlessly from sunrise to deep into the night.",
    foldable_f3_t: "Global Connection",
    foldable_f3_d: "Stay tethered to your world, anywhere on Earth, with integrated SUMĀMAH-Link Satellite Connectivity. Experience crystal-clear calls and high-speed internet, completely free, for life.",
    foldable_f4_t: "Designed for the Elite",
    foldable_f4_d: "The FoldKey marries sophisticated design with robust engineering, protected by a thermodynamic cooling system that keeps performance optimal, even under the most demanding conditions.",
    notebook_title: 'SUMĀMAH Aura',
    notebook_intro: "Beyond the confines of the office or the reach of conventional networks, the SUMĀMAH Aura redefines the workspace. This ultra-premium notebook is a testament to unbridled innovation, designed for visionaries who command their environment, not the other way around.",
    notebook_f1_t: "Boundless Energy",
    notebook_f1_d: "The Aura integrates a vast, high-efficiency solar array seamlessly into its chassis, providing continuous, self-sufficient power. Embrace true portability with Zero Battery dependency and an impressive 72-hour reserve, ensuring your work never halts, day or night.",
    notebook_f2_t: "Unrivaled Connectivity",
    notebook_f2_d: "Equipped with direct SUMĀMAH-Link Satellite Connectivity, the Aura offers a permanent, high-speed gateway to the internet and communication, from the heart of the city to the remotest corners of the globe. no limits, ever.",
    notebook_f3_t: "Peak Performance, Perfect Cooling",
    notebook_f3_d: "Our advanced thermodynamic cooling system ensures the powerful processor and solar charging mechanisms operate at peak efficiency, even in extreme temperatures. Experience relentless performance without compromise.",
    notebook_f4_t: "Crafted for Visionaries",
    notebook_f4_d: "Lightweight, durable, and exquisitely designed, the Aura is more than a notebook; it is a declaration of complete digital autonomy, empowering you to create, connect, and lead from anywhere.",
    notebook_desc: 'Crafted from pure chrome-finished aluminum—never black.',
    about_back: 'Return',
    about_title: 'The Vision of S3Ts',
    about_subtitle: 'Ethics through Engineering.',
    about_p1: 'S3Ts is a movement to restore human dignity. Founded by inventor Abdelwahid Habibullah Adam Banu Hashim, we eliminate toxic mining to end human exploitation.',
    about_founder_role: 'Entrepreneur & Inventor',
    about_founder_name: 'Abdelwahid Habibullah Adam Banu Hashim',
    about_founder_title: 'Architect of the 3 Zeros',
    about_zero1: 'Zero Batteries',
    about_zero1_desc: 'Nano-Optic Solar energy. No lithium.',
    about_zero2: 'Zero Exploitation',
    about_zero2_desc: 'Mining-free supply chain.',
    about_zero3: 'Zero Bills',
    about_zero3_desc: 'Free lifelong global satellite internet.',
    about_vision_strong: 'Innovation for Humanity.',
    about_vision_p2: 'This is my invention. Technology that doesn\'t cost a human life.',
    about_vision_end: 'S3Ts: Ethical. Powerful. Real.',
  },
  ar: {
    nav_pro3: 'برو 3.0',
    nav_foldable: 'SUMĀMAH F',
    nav_notebook: 'SUMĀMAH Aura',
    nav_store: 'المتجر',
    nav_chat: 'S3Ts شات',
    nav_telecom: 'اتصالات',
    nav_fintech: 'S3Ts فينتك',
    nav_fitness: 'S3Ts لياقة',
    nav_cv: 'S3Ts سيرة ذاتية',
    nav_tax: 'S3Ts نوفا تاكس',
    nav_search: 'بحث',
    nav_account: 'الحساب',
    hero_title: 'S3Ts برو 3.0',
    hero_cta: '',
    tech_chat: 'S3Ts شات',
    tech_chat_desc: 'اتصالات مشفرة من الجيل القادم.',
    bio_tag: 'Neural Core A2X',
    bio_title: 'ذكاء كمي',
    bio_desc: '48 نواة ذكاء عصبي مخصصة.',
    energy_tag: 'بصريات شمسية',
    energy_title: 'صفر ليثيوم',
    energy_desc: 'خلايا شمسية نانو بصرية توفر طاقة لا نهائية.',
    energy_lifespan: 'دائم',
    energy_reserve: '72 ساعة احتياطي',
    tech_title: 'المجموعة',
    tech_subtitle: '',
    footer_products: 'المنتجات',
    footer_support: 'الدعم',
    footer_explore: 'استكشف',
    footer_legal: 'قانوني',
    footer_lang: 'العربية',
    store_crumb: 'المتجر',
    store_tagline: '',
    store_price: 'السعر',
    store_stock: 'متوفر',
    store_finish: 'اللون',
    store_core: 'المحرك العصبي',
    store_core_name: 'S3Ts Neural Core A2X',
    store_included: 'أساسي',
    store_add: 'أضف إلى الحقيبة',
    store_view_specs: 'المواصفات التقنية',
    store_warranty_title: 'ضمان S3Ts',
    store_warranty_desc: 'سنتان من الحماية العالمية',
    store_solar_title: 'ضمان شمسي',
    store_solar_desc: 'صحة بطارية دائمة',
    foldable_title: 'SUMĀMAH F',
    foldable_intro: "في عالم يتطلب كلاً من الرشاقة والعمق، يأتي SUMĀMAH FoldKey ليقدم الحل. هذا ليس مجرد هاتف ذكي قابل للطي؛ إنه إعادة تصور لإنتاجية الهاتف المحمول، صُمم لأولئك الذين يرفضون المساومة على التواصل.",
    foldable_f1_t: "تحكم ملموس",
    foldable_f1_d: "افتح الجهاز لتكتشف لوحة مفاتيح صغيرة فعلية مصممة بدقة، توفر سرعة ودقة طباعة لا ميل لهما لرسائل البريد الإلكتروني والمستندات والرسائل الآمنة.",
    foldable_f2_t: "طاقة لا نهائية",
    foldable_f2_d: "مدعوم بتقنية Zero Battery الثورية التي تعتمد بنسبة 100% على الطاقة الشمسية، يضمن FoldKey عدم انقطاع أفكارك أبداً بسبب انخفاض الشحن.",
    foldable_f3_t: "اتصال عالمي",
    foldable_f3_d: "ابقَ مرتبطاً بعالمك في أي مكان على الأرض من خلال اتصال SUMĀMAH-Link المدمج بالأقمار الصناعية. إنترنت عالي السرعة، مجاناً تماماً، مدى الحياة.",
    foldable_f4_t: "مصمم للنخبة",
    foldable_f4_d: "يجمع FoldKey بين التصميم المتطور والهندسة القوية، محمياً بنظام تبريد حراري يحافظ على الأداء الأمثل حتى في أصعب الظروف.",
    notebook_title: 'SUMĀMAH Aura',
    notebook_intro: "خلف حدود المكتب أو وصول الشبكات التقليدية، يعيد SUMĀMAH Aura تعريف مساحة العمل. هذا الكمبيوتر المحمول فائق الجودة هو شهادة على الابتكار غير المقيد، مصمم للرؤيويين الذين يتحكمون في بيئتهم.",
    notebook_f1_t: "طاقة بلا حدود",
    notebook_f1_d: "يدمج Aura مصفوفة شمسية واسعة وعالية الكفاءة بسلاسة في هيكله، مما يوفر طاقة مستمرة وذاتية الكفاءة. تمتع بقابلية حقيقية للتنقل مع الاعتماد على تقنية Zero Battery.",
    notebook_f2_t: "اتصال لا يضاهى",
    notebook_f2_d: "مزود باتصال مباشر عبر القمر الصناعي SUMĀMAH-Link، يوفر Aura بوابة دائمة وعالية السرعة للإنترنت والاتصالات، من قلب المدينة إلى أبعد أركان العالم.",
    notebook_f3_t: "أداء ذروة، تبريد مثالي",
    notebook_f3_d: "يضمن نظام التبريد الديناميكي الحراري المتطور لدينا أن يعمل المعالج القوي وآليات الشحن الشمسي بأقصى كفاءة، حتى في درجات الحرارة القصوى.",
    notebook_f4_t: "مصنوع للرؤيويين",
    notebook_f4_d: "خفيف الوزن، متين، ومصمم بشكل رائع؛ Aura هو أكثر من مجرد كمبيوتر محمول، إنه إعلان عن الاستقلال الرقمي الكامل، مما يمنحك القوة للإبداع والاتصال والقيادة من أي مكان.",
    notebook_desc: 'مصنوع من ألومنيوم الكروم الخالص - لا يتوفر بالأسود أبداً.',
    about_back: 'عودة',
    about_title: 'رؤية S3Ts',
    about_subtitle: 'الأخلاق عبر الهندسة.',
    about_p1: 'S3Ts هي حركة لاستعادة الكرامة الإنسانية. أسسها المخترع عبد الواحد حبيب الله آدم بنو هاشم للقضاء على الاستغلال البشري.',
    about_founder_role: 'رائد أعمال ومخترع',
    about_founder_name: 'عبد الواحد حبيب الله آدم بنو هاشم',
    about_founder_title: 'مؤسس رؤية الأصفار الثلاثة',
    about_zero1: 'صفر بطاريات',
    about_zero1_desc: 'طاقة نانو شمسية. بدون ليثيوم.',
    about_zero2: 'صفر استغلال',
    about_zero2_desc: 'سلسلة توريد خالية من التعدين.',
    about_zero3: 'صفر فواتير',
    about_zero3_desc: 'إنترنت فضائي عالمي مجاني مدى الحياة.',
    about_vision_strong: 'الابتكار من أجل الإنسانية.',
    about_vision_p2: 'هذا اختراعي. تكنولوجيا لا تكلف حياة إنسان.',
    about_vision_end: 'S3Ts: أخلاقية. قوية. حقيقية.',
  }
};
